### ISSUE TITLE
Filtering files by MimeType instead of extension

### ISSUE THREAD

**Issue by trindadeptr** [eXsio/vaadin-plupload#13]
Hello

I'm using this addon and it is amazing. I have a small issue, I am filtering file by extension, as suggested in the documentation. 

It would be possible to filter instead by MimeType? For example I want to import only .png files. But if I try to import a file without extension and Mimetype is "image/png" I would like to accept it. This can be done before sending the file? After sending the file I think it can be done easily, but I would like to do this before sending it.

I would appreciate any tips to guide me in the right direction, thanks in advance.

**Comment by frmst** [comment]
Hi, Thank you for using the plugin.

The filtering functionality is provided by client-side Plupload JS library. My plugin is just a connector between Vaadin and the JS library, so it relays the filtering logic from server side code to client side. In order to maintain compatibility with the JS lib, I thing we'll have to stick with the extension filtering.

**Comment by trindadeptr** [comment]
Ok, we will rely on extension filtering then, thanks for your reply.
