### ISSUE TITLE
A version without temp files?

### ISSUE THREAD

**Issue by mstahv** [eXsio/vaadin-plupload#6]
Any plans to implement a "streaming" version, without temp files? I tried this in Bluemix, but it didn't manage to create temp file. In addition to be more compatible, streaming would also be bit more efficient in some cases (if file handling will take long in server as well).

Thanks for a great library! I hope I can soon drop supporting EasyUploads totally. This is way more modern and cooler project.

**Comment by eXsio** [comment]
Hey, thanks for the kind words!

Actually the library uses the Streaming API from Apache Commons FileUpload and appends subsequent chunks to the target file without using any temporary files. The first version used the standard API, but the resource (both HDD for temporary files and RAM for keeping entire uploaded chunks in the heap) consumption was too great. Did You mean a version, in which we'd drop writng the uploaded file to a disk and keep it in memory? Because that would work efficiently only for small files.

**Comment by mstahv** [comment]
I mean a version where the developer would get an InputStream we would handle.

**Comment by eXsio** [comment]
I understand. I can imagine the advantages, but since the uploaded file is chunked, the whole file would have to be stored in memory until the upload finishes. It would be good for small files, but imagine that 4 users uploading 200MB file each. The heap would grow by 800MB... 

I understand though, that there are some conditions, where creating temp files is not an option because of the environmental restictions. I will investigate the possibility to optionally disable temp files and use streams instead.

**Comment by mstahv** [comment]
Why can't the stream from servlet be passed to consumer? Directly or with a small extra buffer only. Synchronisation will be hard, but I think this should be possible.

**Comment by eXsio** [comment]
Hi

I added new server-side event: ChunkUploaded. The handler for this event receivers an instance of PluploadChunk with the reference to the InputStream (and other data like file name, number of total chunks and number of current chunk). However this particular handler cannot update the UI or any UI related stuff, as it's being passed directly to the RequestHandler instance. That was the only way, because the Plupload library doesnt send enough data on client-side ChunkUploaded event, to verify which chunk to get from the Receiver (which acts as RequestHandler). Furthermore I didn't want to add yet another RPC call to the server, on each chunk upload. As a result, this is purely server-side event. Hope this solution satisfies You :)

P.S.

There's version 1.6.0 available in the Directory.

**Comment by eXsio** [comment]
Hey, just a head up. There's a new version od the add on in the Directory (2.0.0) with completely refactored way of handling uploads on the server side. I think it will nicely solve Your issue and all the similar ones.
